site_name: httpdbg
site_url: https://httpdbg.readthedocs.org
site_description: httpdbg is a tool to trace the HTTP(S) client requests in your python code. 
site_author: cle-b

nav:
    - httpdbg: index.md
    - getting started: getting_started.md
    - pyhttpdbg: pyhttpdbg.md
    - pytest: pytest.md
    - notebook: notebook.md
    - user interface: ui.md

theme: readthedocs