site_name: httpdbg
site_url: https://httpdbg.readthedocs.org
site_description: httpdbg is a tool to trace the HTTP(S) client requests in your python code. 
site_author: cle-b

nav:
    - Introduction: index.md
    - Getting started: getting_started.md
    - pyhttpdbg: pyhttpdbg.md
    - Test frameworks: test.md
    - Notebook: notebook.md
    - User interface: ui.md

theme: material

repo_url: https://github.com/cle-b/httpdbg
repo_name: cle-b/httpdbg

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
